language: cpp
dist: trusty
sudo: required
compiler: gcc
before_install:
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install pkg-config zip zlib1g-dev unzip python
  - wget https://github.com/bazelbuild/bazel/releases/download/0.25.0/bazel-0.25.0-installer-linux-x86_64.sh
  - chmod +x bazel-0.25.0-installer-linux-x86_64.sh
  - ./bazel-0.25.0-installer-linux-x86_64.sh --user
script:
  - $HOME/bin/bazel build ...
  - $HOME/bin/bazel --batch test ... --test_output=errors --noshow_progress
