version: '1.0.{build}'

pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

clone_folder: C:\projects\jwt_dump

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cd C:\projects\jwt_dump

build_script:
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" ..
  - nmake
  - nmake /A test
