name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: "Build and test (OS: ${{ matrix.os }})"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Build and run
        shell: bash
        run: |
          cmake -B build -S .
          cd build
          cmake --build .
          ctest -V
